apiVersion: v1
kind: Service
metadata:
  name: dockercami-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: dockercami
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
