- hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Checking the user name
    shell: /usr/bin/whoami
    register: username

  - name: Debugging the whoami username
    debug: msg={{ username.stdout }}

  - name: Touch a file
    file:
      path: ./linuxtips
      state: touch
      group: camillamartins
      owner: camillamartins

  - name: List file
    command: ls -la ./linuxtips
    register: filelinuxtips

  - name: Log file
    debug: msg={{ filelinuxtips.stdout }}